general:
  do_all_steps: True # If this is set to True: it will override individual module do_step flags and run every step.
  remove_images_at_end: False # If True: the processed image files will be deleted after pipeline is finished (set to True if there are storage concerns)
  working_dir: 'path/to/directory/containing/raw/data' # Path to the directory containing the night's data (and in which the reduction will be saved)
  reduction_dir: 'reduction_new/' # Reduction directory name
  sub_dir_list: [ 'cals', 'trace', 'object_files', 'spectrum_files', 'wavecal', 'radial_velocity' ] # Reduction sub-directories to create at start of reduction run
  header_info_file_name: 'header_info.csv' # Name for the header info file
  binning: True # True if it is 2x2 binned

calibrations:
  do_step: False
  bias_image_type: 'zero' # The header image type for the bias frames
  flat_image_type: 'flat' # The header image type for the flat frames
  flat_object_names_to_discard: [ 'FF integration time test' ] # Object names to exclude from the creation of the flat field
  bias_bpm_percentile: 99.9 # Percentile for the bias to mark above as a bad pixel
  flat_field_bpm_limit: 1.0e-4 # Flat field value to mark below as a bad pixel

image_process:
  do_step: False
  arc_lamp_image_type: 'comp' # The header image type for the arc lamp spectra
  valid_arc_lamp_object_names: [ 'thar', 'a' ] # Object names to include as arc lamp frames
  invalid_science_object_names: [ 'test' ] # Object names to exclude as science frames
  cosmic_subtract: True # Create object spectral cube with cosmic ray subtraction
  cosmic_subtract_niter: 4 # Set the number of iterations for the cosmic subtraction

trace:
  do_step: False
  order_xdisp_trace_width: 20 # Rough estimate of the cross dispersion width of a flat field order trace (in pixels)
  order_start_index: -33 # The dispersion-direction index to start searching for the order traces, just within the overscan region
  order_center_method: 'peak_find' # The method to find the initial guess for center of the order trace at the edge. Either peak_find or gradient_threshold
  trace_poly_degree: 2 # The polynomial degree to fit to the trace
  trace_poly_fit_start_index: 512 # The starting dispersion-direction index to fit the trace (to exclude the edge that can have issues)
  number_of_orders: 58 # The number of orders we will extract -- if fewer are found, then the fit trace is extended

extraction:
  do_step: False
  reverse_traced_orders: True # If True, reverse the order trace array. For the Tull, this is True so that order index 0 is bluest (rather than reddest).
  order_xdisp_width_extract: 16 # The cross dispersion width of an order for extraction (in pixels)
  science_extract_type: 'optimal_extraction' # The extraction method for science frames. Must be 'optimal_extraction' or 'sum_extraction'
  lamp_extract_type: 'sum_extraction' # The extraction method for arc lamp frames. Must be 'optimal_extraction' or 'sum_extraction'
  science_background_subtract: 'fixed' # The background subtraction method for science frame extraciton. Must be 'fixed', 'fit', 'none'
  lamp_background_subtract: 'none' # The background subtraction method for arc lamp frame extraciton. Must be 'none' or 'subtract'

wavecal:
  do_step: False
  min_arc_exp_time: 30 # The minimum exposure time for an arc lamp frame to be used for wavelength calibration
  use_prelim_sol_order_offset: True # Whether an order offset between observation and wavesol guess should be calculated 
  peak_threshold_mad_method: 'chunk_spectrum' # The method for estimating the noise to set prominence level of peak finding algorithm. Either 'full_spectrum' or 'chunk_spectrum'
  lamp_line_peak_threshold_sigma: 5 # The number of sigma above the background to use for the peak finding algorithm to identify lines in the spectrum
  lamp_line_min_separation_pix: 5 # The minimum number of pixels required between lines for the peak finding algorithm
  lamp_line_pix_width_limits: [ 2, 4 ] # The minimum and maximum width of lamp lines in pixels for the peak finding algorithm
  wave_sol_guess: 'prelim_wave_sol.npy' # Name for the preliminary wavelength solution (initial guess)
  line_list: 'thorium_line_list.csv' # List of reference wavelengths of lamp used for wavelenth calibration
  arc_ref_file: 'photron_thar_atlas.csv' # CSV with 'wavelength' and 'flux' of a reference photron ThAr spectrum, for plotting purposes
  max_wave_diff_with_list: 1.0 # The maximum wavelength difference allowed between the preliminary solution for found peaks and the line list to include in fitting the solution
  wave_cal_poly_order: 4 # Polynomial order for the wavelength solution
  vel_resid_sigma_reject: 3 # The sigma level for rejecting velocity residuals in the iterative wavelength solution polynomial fitting

continuum_fit:
  do_step: False
  lower_sigma_reject: 2 # The sigma level for rejecting points below the continuum fit
  upper_sigma_reject: 5 # The sigma level for rejecting points above the continuum fit
  num_spectrum_chunks: 6 # The number of chunks to break the spectrum into (related to the number of spline knots)
  min_knot_spacing: 15 # The minimum knot spacing in wavelength (angstrom)

radial_velocity:
  do_step: True
  recompute_rvs: False # If set to False, will skip files that already have radial velocity extensions
  orders_to_use_file_name: 'good_orders_tull_coude.csv' # File name of the pre-defined orders to use for BF computation
  template_file_name: 'phoenix_t5500_g4.5_m0.0.csv' # File name of the spectrum template for BF computation
  bf_velocity_span: 300 # The velocity span to compute the BF over (in km/s)
  bf_smooth_res: 60000 # The resolution to smooth the BF to (typically same as the instrument resolution)
  n_bootstrap_samples: 2500 # The number of bootstrap samples for BF combination and RV measurement

