from setuptools import setup, find_packages

setup( name = 'tull_coude_reduction',
       description = 'Tull coude spectrograph reduction and analysis pipeline',
       author = 'Danny Krolikowski',
       author_email = 'krolikowski@arizona.edu',
       url = 'https://github.com/krolikowski/tull_coude_reduction',
       license = 'MIT',
       classifiers = [ 'Development Status :: 3 - Alpha',
                       'Intended Audience :: Science/Research',
                       'License :: OSI Approved :: MIT License',
                       'Programming Language :: Python :: 3',
                       'Topic :: Scientific/Engineering :: Astronomy',
                       ],
       project_urls = { 'Documentation': 'https://tull-coude-reduction.readthedocs.io/en/latest/'
                       },
       packages = find_packages(),
       package_data = { 'tull_coude_reduction.data': [ '*.csv', '*.npy' ] },
       python_requires = '>=3',
       install_requires = [ 'numpy==1.23.5',
                            'matplotlib',
                            'scipy',
                            'pandas',
                            'astropy==5.2',
                            'astroscrappy',
                            'saphires',
                            'barycorrpy',
                            'tqdm',
                            'pyyaml',
                            'urllib3==1.26.15',
                            'PyQt5',
                            'emcee',
                            'corner',
                            'pydl'
                            ]
       )